# Generated by Django 4.1.4 on 2023-01-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_docente_periodo_seccion_evaluacion'),
        ('estudiantes', '0002_rename_estudiantes_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clases.evaluacion')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estudiantes.inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estudiantes.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clases.periodo')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estudiantes.matricula'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clases.periodo'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clases.seccion'),
        ),
    ]
