# Generated by Django 4.1.5 on 2023-01-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clases", "0003_alter_clase_options_alter_evaluacion_clase_and_more"),
        (
            "estudiantes",
            "0003_inscripcion_nota_matricula_inscripcion_matricula_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estudiante",
            options={"ordering": ["nombre", "-apellido"]},
        ),
        migrations.AlterModelOptions(
            name="inscripcion",
            options={
                "ordering": [
                    "matricula__estudiante__nombre",
                    "-matricula__estudiante__apellido",
                ]
            },
        ),
        migrations.AlterField(
            model_name="inscripcion",
            name="matricula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inscripciones",
                to="estudiantes.matricula",
            ),
        ),
        migrations.AlterField(
            model_name="inscripcion",
            name="seccion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inscripciones",
                to="clases.seccion",
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="estudiante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="matriculas",
                to="estudiantes.estudiante",
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="inscripcion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="notas",
                to="estudiantes.inscripcion",
            ),
        ),
    ]
