# Generated by Django 4.1.5 on 2023-02-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clases", "0006_alter_evaluacion_options"),
        (
            "estudiantes",
            "0004_alter_estudiante_options_alter_inscripcion_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inscripcion",
            unique_together={("matricula", "seccion", "periodo")},
        ),
        migrations.AlterUniqueTogether(
            name="matricula",
            unique_together={("periodo", "estudiante")},
        ),
    ]
