# Generated by Django 4.1.7 on 2023-02-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_alter_inscripcion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['periodo', 'estudiante__nombre', 'estudiante__apellido']},
        ),
    ]
