# Generated by Django 4.1.7 on 2023-03-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_alter_nota_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['evaluacion__numero']},
        ),
    ]
