# Generated by Django 4.1.7 on 2023-03-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_alter_nota_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='asistencia',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nota_final',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nota_presentacion',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='situacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
