version: '3.9'

services:
  app:
    build: .
    restart: always
    volumes:
      - static_data:/vol/static
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  api:
    image: ghcr.io/inacapi/api:2.0
    restart: always

  proxy:
    build:
      context: ./docker/proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_data:/vol/static
      - certbot_web:/vol/www
      - proxy_dhparams:/vol/proxy
      - certbot_certs:/etc/letsencrypt
    depends_on:
      - app
    env_file:
      - .env

  certbot:
    build:
      context: ./docker/certbot
    command: echo "Skipping certbot..."
    env_file:
      - .env
    volumes:
      - certbot_web:/vol/www
      - certbot_certs:/etc/letsencrypt
    depends_on:
      - proxy

volumes:
  static_data:
  mysql_data:
  certbot_web:
  proxy_dhparams:
  certbot_certs:
