version: '3.9'

services:
  app:
    build: .
    volumes:
      - static_data:/vol/web
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=inacapi
      - MYSQL_DATABASE=inacapi
      - MYSQL_USER=inacapi
      - MYSQL_PASSWORD=inacapi

volumes:
  static_data:
  mysql_data:
