version: '3.9'

services:
  app:
    build: .
    volumes:
      - static_data:/vol/web
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=inacapi
      - MYSQL_DATABASE=inacapi
      - MYSQL_USER=inacapi
      - MYSQL_PASSWORD=inacapi

  proxy:
    build:
      context: ./proxy
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data:
  mysql_data:
