# Generated by Django 4.1.4 on 2023-01-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('inscripciones', '0002_alter_inscripcion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='evaluaciones.evaluacion')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inscripciones.inscripcion')),
            ],
        ),
    ]
