# Generated by Django 4.1.4 on 2023-01-04 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
        ('clases', '0001_initial'),
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clases.clase')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='docentes.docente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='periodos.periodo')),
            ],
        ),
    ]
