# Generated by Django 4.1.4 on 2023-01-04 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodos', '0001_initial'),
        ('estudiantes', '0002_rename_estudiantes_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estudiantes.estudiante')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='periodos.periodo')),
            ],
        ),
    ]
