# Generated by Django 4.1.4 on 2023-01-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='id_estudiante',
            new_name='estudiante',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='id_periodo',
            new_name='periodo',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
