# Generated by Django 4.1.4 on 2023-01-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculas', '0002_rename_id_estudiante_matricula_estudiante_and_more'),
        ('secciones', '0001_initial'),
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='matriculas.matricula')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='periodos.periodo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='secciones.seccion')),
            ],
        ),
    ]
