# Generated by Django 4.1.5 on 2023-01-18 20:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clases", "0002_docente_periodo_seccion_evaluacion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clase",
            options={"ordering": ["semestre", "nombre"]},
        ),
        migrations.AlterField(
            model_name="evaluacion",
            name="clase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="evaluaciones",
                to="clases.clase",
            ),
        ),
        migrations.AlterField(
            model_name="evaluacion",
            name="numero",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="evaluacion",
            name="porcentaje",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="seccion",
            name="clase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="secciones",
                to="clases.clase",
            ),
        ),
    ]
