# Generated by Django 4.1.5 on 2023-01-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clases", "0003_alter_clase_options_alter_evaluacion_clase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacion",
            name="numero",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="evaluacion",
            unique_together={("clase", "numero")},
        ),
    ]
