# Generated by Django 4.1.7 on 2023-02-25 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0006_alter_evaluacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['nombre', 'apellido']},
        ),
    ]
