# Generated by Django 4.1.7 on 2023-02-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_alter_docente_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seccion',
            unique_together=set(),
        ),
    ]
