# Generated by Django 4.1.7 on 2023-03-01 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0010_alter_evaluacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evaluaciones', to='clases.seccion'),
        ),
    ]
